name: Publish React Components Package

# on:
#   release:
#     types: [created]

on:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install Dependencies
        run: npm install

      - name: Test
        run: npm test

      - name: Build
        run: CI=true npm run build

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
